version: '3.8'

services:
  meilisearch:
    image: 'getmeili/meilisearch:latest'
    container_name: meilisearch_db
    ports:
      - '7700:7700'
    volumes:
      - ./meili_data:/data.ms
    environment:
      - MEILI_MASTER_KEY=aSampleMasterKey
      - MEILI_ENV=development
    restart: always

  app:
    image: 'getmeili/meilisearch:latest' 
    ports:
      - '7700:7700'
    environment:
      - MEILI_URL=http://meilisearch:7700
      - MEILI_MASTER_KEY=aSampleMasterKey
    depends_on:
      - meilisearch
    restart: always