name: market-lens-backend
services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: django
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      database:
        condition: service_healthy
      search_engine:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - DEBUG=${DEBUG}
      - MEILI_URL=${MEILI_URL}
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - market_lens_network
    restart: always

  database:
    image: 'postgres:15-alpine'
    env_file:
      - .env
    container_name: market_lens_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 6
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - market_lens_network
    restart: always

  offer_crawler:
    build:
      context: .
      dockerfile: offer_crawler/Dockerfile
    container_name: offer_crawler
    env_file:
      - .env
    working_dir: /app
    command: sh -c "scrapy crawl badrgrb && scrapy crawl frensia && scrapy crawl hardwaremarket && scrapy crawl sigma"
    depends_on:
      database:
        condition: service_healthy
      search_engine:
        condition: service_healthy
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./offer_crawler:/app
      - ./backend:/backend:ro
    networks:
      - market_lens_network
    restart: always

  search_engine:
    image: 'getmeili/meilisearch:v1.7.0'
    env_file:
      - .env
    container_name: market_lens_meilisearch
    ports:
      - "7700:7700"
    volumes:
      - ./meili_data:/meili_data
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      - MEILI_ENV=development
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7700/health" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - market_lens_network
    restart: always

volumes:
  database_data:
  meili_data:

networks:
  market_lens_network:
    driver: bridge
