# Generated by Django 5.2.12 on 2026-06-16 16:26

import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('vendor', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('raw_features', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'scraped_items',
                'indexes': [models.Index(fields=['url'], name='scraped_ite_url_dd47da_idx'), models.Index(fields=['vendor'], name='scraped_ite_vendor_849df1_idx'), django.contrib.postgres.indexes.GinIndex(fields=['raw_features'], name='scraped_ite_raw_fea_c206cb_gin')],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_in_stock', models.BooleanField(default=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='users.scrapeditem')),
            ],
            options={
                'db_table': 'price_history',
                'ordering': ['-scraped_at'],
                'indexes': [models.Index(fields=['scraped_at'], name='price_histo_scraped_6574ce_idx')],
            },
        ),
    ]
