# Generated by Django 5.2.12 on 2026-09-12 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_wishlist_product_wishlist_products_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pricehistory',
            new_name='price_histo_item_id_790372_idx',
            old_name='price_item_scraped_idx',
        ),
    ]
